### ISSUE TITLE
post:git-ui-features,par:c3luY2l0c2hvdWxk

### ISSUE THREAD

**Issue by tarsius** [arxanas/blog#15]
You have to define what "sync" and "all" mean. I am guessing you mean that every local branch whose configure upstream is a remote tracking branch should be updated to point at the same commit. If so, what is the "obviously only correct thing to do" if a fast-forward is not possible, in you opinion? Edit: Okay I saw your `git sync` now. It's neat, but I think it would make more sense to sync with the respective upstream than the main branch. Is it possible to *not* sync certain branches?

**Comment by arxanas** [comment]
@epage Would git-stack support this workflow?

**Comment by epage** [comment]
The old `git stack --pull` will syncs only
- Development branches
- By the current user
- That are not too stale

There is a flag, `--stack`, and a config field to control whether to only sync
- the current branch and all dependents
- everything part of your current stack (so includes branches off of a parent commit)
- all stacks off of your base branch (e.g. `main`)
- all stacks

I have recently been reworking this workflow with `git stack sync` (which `git stack alias --register` will alias to `git sync`).    Currently it is hard coded to "every branch off your current branch" though it has the author auto-rules.

An auto-rule I have been considering is when `--stack` is set to something that will pull in other stacks that it would skip stacks with a pushed branch so it doesn't unnecessarily rebase branches under review.
