### ISSUE TITLE
post:git-ui-features,par:cmV3b3JkaXRzaG91

### ISSUE THREAD

**Issue by tarsius** [arxanas/blog#16]
In Magit place the cursor on the commit in question press `r w`. The current message appears in a buffer. Edit it and press `C-c C-c` when done. Yes, it uses the horrible `git rebase`, but as you said, nothing can go wrong when editing a commit message, so that is mostly an implementation details. (Admittedly it only works if the commit is reachable from HEAD.)

**Comment by arxanas** [comment]
Thanks for your comment. I've updated the table in the article.
