### ISSUE TITLE
post:plrust-przyrostowe-czasy-testowania,par:ZG9wdXN6Y3phbG5l

### ISSUE THREAD

**Issue by enedil** [arxanas/blog#24]
> łączenia [ang. “linking”]

w polskiej literaturze to jest `konsolidacja`

> szybkich czasów testowania

Czas nie może być szybki. Czynności mogą być. Więc np. `krótkich czasów testowania.

> Jeśli chodzi o poprawę relatywną, to znaczna, ale jeśli chodzi o poprawę absolutną, sądzę, że jest raczej słaba

ok, można tak powiedzieć, ale raczej bym mówił `względna`, `bezwzględna`, a nie `relatywna`, `absolutna`. (szczególnie w przypadku tego drugiego słowa)

> większość moich użytkowników instaluje przez cargo

trochę brakuje tutaj przedmiotu zdania. Np. `instaluje program przez cargo`. 

> dla mniejszej crate testowania z niewieloma zależności

To jest raczej `testowe crate`. Ponadto `niewieloma zależnościami`.

> Dokumentacji cargo nextest ostrzega, że niektóre systemy

Powinno być `Dokumentacja`

> który niedawno stworzyłem bez dużo zaleźności

Powinno być `bez wielu`. Niestety nie znam dobrego wyjaśnienia czemu tak ma być, natomiast podejrzewam, że odnosi się to do formy gramatycznej jaką by `dużo` musiało osiągnąć w zdaniu zaprzeczającym tej wielości.

> ich zmniejszenie nie wydawało się poprawę czasu kompilacji

Powinno być `nie zdawało się poprawiać`. Po pierwsze bezokolicznik (poprawiać). `wydawało się` jest względnie ok, ale tutaj szybsza do wymowy forma lepiej pasuje. 

> Niestety, są dużo makr proceduralnych

Powinno być `Niestety, jest dużo makr proceduralnych`

> To najwięcej, co mogę skrócić przyrostowe czasy testowania

Powinno być `To najwięcej, jak mogę skrócić przyrostowe czasy testowania`. Jak czytałem `To najwięcej, co mogę`, to oczekiwałem `To najwięcej, co mogę [zrobić, by coś osiągnąć]`.

**Comment by arxanas** [comment]
@enedil Dziękuję bardzo! Wprowadziłem sugerowane przez Ciebie zmiany.
